// This is an autogenerated file from Firebase Studio.
'use server';

import { coffeeChatbotRecommendations, CoffeeChatbotRecommendationsInput } from '@/ai/flows/coffee-chatbot';

export async function getCoffeeRecommendation(input: CoffeeChatbotRecommendationsInput): Promise<string> {
    try {
        const result = await coffeeChatbotRecommendations(input);
        return result.recommendation;
    } catch (error) {
        console.error("AI recommendation failed:", error);
        return "I'm sorry, I'm having trouble coming up with a recommendation right now. Please try again later.";
    }
}
